services:
  backend: 
    build:
      context: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - backend-network
    depends_on:
      mysql:
        condition: service_healthy
      redis-container:
        condition: service_started
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost' ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis-container:
    image: redis:latest
    container_name: redis-container
    restart: always
    env_file: .env
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  mysql_data:


